"""D-292 — DDL 해석기(`parse_ddl`): 엔진별 덤프 형식 · 경고 · MCP 수집과의 스냅샷 동등성.

핵심 계약: 같은 구조라면 DDL 해석 결과의 스냅샷 해시가 MCP `get_full_schema` 수집 결과와 같다 —
그래야 DDL로 등록한 기준선을 뒤에 MCP로 변경 점검해도 가짜 차이가 나지 않는다. MCP 쪽은 실제
`DBHubClient`에 가짜 세션을 붙여(서비스 테스트 공용 픽스처) 엔진별 MCP 서버 응답 표기
(`information_schema.data_type` · DB2 `TYPENAME` · bare 키 규칙)를 흉내 낸다.

이름은 전부 가상(`app_*`·`t_*`) — 운영 스키마 리터럴을 쓰지 않는다. 네트워크·Redis·LLM 0.
"""

from __future__ import annotations

from typing import Any

import pytest

from src.domain.schema_snapshot import build_snapshot
from src.schema_cache.db_structure_service import schema_dict_from_full_schema
from src.schema_cache.ddl_schema_parser import MAX_WARNINGS, parse_ddl, split_statements
from tests.test_schema_cache.test_plan104_service_fixtures import (
    FakeMCPSession,
    FakeTable,
    client_factory,
)

PG_DUMP = """
SET statement_timeout = 0;
SELECT pg_catalog.set_config('search_path', '', false);
CREATE FUNCTION public.touch() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated := now(); RETURN NEW; END; $$;
CREATE TYPE public.t_mood AS ENUM ('a', 'b');
CREATE TABLE public.t_node (
    id integer NOT NULL,
    parent_id integer,
    node_type character varying(50) DEFAULT 'x'::character varying,
    created timestamp(6) without time zone DEFAULT now(),
    tags text[],
    mood public.t_mood,
    amount numeric(10,2) CHECK (amount IS NOT NULL)
);
COMMENT ON TABLE public.t_node IS '노드';
COMMENT ON COLUMN public.t_node.node_type IS '노드 유형';
CREATE TABLE public.t_asset (
    id bigint NOT NULL,
    node_id integer,
    ok boolean
);
CREATE TABLE ops.t_log (seq bigint NOT NULL, body text);
CREATE INDEX ix_node_parent ON public.t_node USING btree (parent_id);
ALTER TABLE ONLY public.t_node ADD CONSTRAINT t_node_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.t_asset ADD CONSTRAINT t_asset_pkey PRIMARY KEY (id);
ALTER TABLE ONLY ops.t_log ADD CONSTRAINT t_log_pkey PRIMARY KEY (seq);
ALTER TABLE ONLY public.t_asset
    ADD CONSTRAINT t_asset_node_fk FOREIGN KEY (node_id) REFERENCES public.t_node(id);
ALTER TABLE public.t_node OWNER TO app_owner;
CREATE TEMP TABLE t_tmp (a int);
CREATE VIEW public.v_node AS SELECT id FROM public.t_node;
"""

DB2_LOOK = """
CONNECT TO APPDB;
CREATE TABLE "APP     "."T_NODE"  (
          "ID" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH +1 INCREMENT BY +1) ,
          "NAME" VARCHAR(100 OCTETS) ,
          "FLAG" CHAR(1 OCTETS) FOR BIT DATA NOT NULL WITH DEFAULT 'N' ,
          "TS" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP ,
          "AMT" DECIMAL(10,2) )
         IN "USERSPACE1"
         ORGANIZE BY ROW;
ALTER TABLE "APP     "."T_NODE" ADD CONSTRAINT "PK_NODE" PRIMARY KEY ("ID");
create table app.t_child (
    id int not null primary key,
    node_id bigint,
    foreign key (node_id) references app.t_node
);
COMMENT ON COLUMN "APP     "."T_NODE"."NAME" IS '이름';
COMMENT ON "APP"."T_CHILD" ("NODE_ID" IS '노드');
--#SET TERMINATOR @
CREATE TRIGGER APP.TRG AFTER INSERT ON APP.T_NODE FOR EACH ROW BEGIN ATOMIC SET A = 1; END@
"""

MARIADB_DUMP = r"""
/*!40101 SET NAMES utf8mb4 */;
DROP TABLE IF EXISTS `t_item`;
CREATE TABLE `t_item` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '아이디',
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'it''s',
  `owner_id` bigint(20) DEFAULT NULL,
  `payload` json DEFAULT NULL,
  `flag` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `ix_owner` (`owner_id`),
  CONSTRAINT `fk_owner` FOREIGN KEY (`owner_id`) REFERENCES `t_owner` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='항목 # 주석 아님';
INSERT INTO `t_item` VALUES (1,'a;b\'',NULL,NULL,0);
DELIMITER ;;
CREATE TRIGGER trg BEFORE INSERT ON t_item FOR EACH ROW BEGIN SET NEW.flag = 1; END ;;
DELIMITER ;
CREATE TABLE t_owner (id BIGINT PRIMARY KEY) # 줄 끝 주석
;
"""


def _columns(result: Any, table: str) -> dict[str, tuple[str, bool, bool, str | None]]:
    return {
        c.name: (c.data_type, c.nullable, c.is_primary_key, c.references)
        for c in result.schema.tables[table].columns
    }


def _snapshot_of(schema: Any) -> tuple[dict[str, Any], dict[str, Any]]:
    schema_dict, table_schemas = schema_dict_from_full_schema(schema)
    return schema_dict, build_snapshot(schema_dict, table_schemas)


# ──────────────────────────────────────────────
# 엔진별 덤프 형식
# ──────────────────────────────────────────────


class TestPostgres:
    def test_pg_dump_tables_types_keys(self):
        result = parse_ddl(PG_DUMP, "postgresql")

        assert list(result.schema.tables) == ["t_node", "t_asset", "ops.t_log"]
        assert result.schema.tables["t_node"].schema_name == "public"
        assert result.schema.tables["ops.t_log"].schema_name == "ops"
        assert _columns(result, "t_node") == {
            "id": ("integer", False, True, None),  # PK는 NOT NULL
            "parent_id": ("integer", True, False, None),
            "node_type": ("character varying", True, False, None),
            "created": ("timestamp without time zone", True, False, None),
            "tags": ("ARRAY", True, False, None),
            "mood": ("USER-DEFINED", True, False, None),
            "amount": ("numeric", True, False, None),  # CHECK 안의 NOT NULL은 속성이 아니다
        }
        assert _columns(result, "t_asset")["node_id"] == ("integer", True, False, "t_node.id")
        assert result.schema.relationships == [{"from": "t_asset.node_id", "to": "t_node.id"}]
        assert result.warnings == []

    def test_pg_dump_comments_and_skipped_statements(self):
        result = parse_ddl(PG_DUMP, "postgresql")

        assert result.comments == {"t_node": "노드", "t_node.node_type": "노드 유형"}
        assert result.skipped == {
            "SET": 1, "SELECT": 1, "CREATE FUNCTION": 1, "CREATE TYPE": 1, "CREATE INDEX": 1,
            "ALTER TABLE (그 밖의 변경)": 1, "CREATE TEMPORARY TABLE": 1, "CREATE VIEW": 1,
        }
        # 함수 본문(달러 인용)의 `;`가 문장을 자르지 않는다 — 문장 17개(본문 `;`까지 세면 19)
        assert result.statement_count == 17

    def test_unquoted_identifiers_fold_to_lower(self):
        ddl = 'CREATE TABLE T_Up (Id INT PRIMARY KEY, "MixedCase" TEXT);'
        result = parse_ddl(ddl, "postgresql")

        assert list(result.schema.tables) == ["t_up"]
        assert [c.name for c in result.schema.tables["t_up"].columns] == ["id", "MixedCase"]


class TestDB2:
    def test_db2look_padded_schema_upper_types_and_fk_to_pk(self):
        result = parse_ddl(DB2_LOOK, "db2")

        assert list(result.schema.tables) == ["T_NODE", "T_CHILD"]  # DB2 키는 항상 bare
        # db2look의 8자 채움 스키마명은 MCP(`TRIM(TABSCHEMA)`)처럼 뒤 공백을 뗀다
        assert result.schema.tables["T_NODE"].schema_name == "APP"
        assert result.schema.tables["T_CHILD"].schema_name == "APP"
        assert _columns(result, "T_NODE") == {
            "ID": ("BIGINT", False, True, None),
            "NAME": ("VARCHAR", True, False, None),
            "FLAG": ("CHARACTER", False, False, None),
            "TS": ("TIMESTAMP", False, False, None),
            "AMT": ("DECIMAL", True, False, None),
        }
        # 대상 컬럼이 없는 REFERENCES는 대상 PK로 푼다
        assert _columns(result, "T_CHILD")["NODE_ID"] == ("BIGINT", True, False, "T_NODE.ID")
        assert result.schema.relationships == [{"from": "T_CHILD.NODE_ID", "to": "T_NODE.ID"}]
        assert result.warnings == []

    def test_db2_comments_terminator_and_skipped(self):
        result = parse_ddl(DB2_LOOK, "db2")

        assert result.comments == {"T_NODE.NAME": "이름", "T_CHILD.NODE_ID": "노드"}
        # `--#SET TERMINATOR @` 뒤 트리거 본문의 `;`는 문장 끝이 아니다
        assert result.skipped == {"CONNECT": 1, "CREATE TRIGGER": 1}

    def test_default_schema_fills_unqualified_tables(self):
        result = parse_ddl("CREATE TABLE T_A (ID INT NOT NULL);", "db2", default_schema="APPS")

        assert result.schema.tables["T_A"].schema_name == "APPS"


class TestMariaDB:
    def test_mysqldump_backticks_types_comments(self):
        result = parse_ddl(MARIADB_DUMP, "mariadb")

        assert list(result.schema.tables) == ["t_item", "t_owner"]
        assert _columns(result, "t_item") == {
            "id": ("int", False, True, None),  # unsigned·AUTO_INCREMENT는 타입 표기에 넣지 않는다
            "name": ("varchar", True, False, None),
            "owner_id": ("bigint", True, False, "t_owner.id"),
            "payload": ("longtext", True, False, None),  # MariaDB JSON = LONGTEXT 별칭
            "flag": ("tinyint", False, False, None),
        }
        assert _columns(result, "t_owner") == {"id": ("bigint", False, True, None)}
        assert result.comments == {
            "t_item.id": "아이디", "t_item.name": "it's", "t_item": "항목 # 주석 아님",
        }
        assert result.skipped == {"DROP TABLE": 1, "INSERT": 1, "CREATE TRIGGER": 1}
        assert result.warnings == []

    def test_qualifier_against_default_database(self):
        ddl = "CREATE TABLE app.t_a (id INT); CREATE TABLE other.t_b (id INT);"

        assert list(parse_ddl(ddl, "mariadb", default_schema="app").schema.tables) == [
            "t_a", "other.t_b",
        ]
        # 기본 database를 모르면 한정자를 무시한다(덤프 하나 = database 하나)
        assert list(parse_ddl(ddl, "mariadb").schema.tables) == ["t_a", "t_b"]


# ──────────────────────────────────────────────
# 경고 — 조용히 버리지 않는다
# ──────────────────────────────────────────────


class TestWarnings:
    def test_unreadable_definitions_are_reported(self):
        ddl = """
        CREATE TABLE t_copy AS SELECT * FROM t_src;
        CREATE TABLE t_like (LIKE t_src INCLUDING ALL);
        CREATE TABLE t_a (id int PRIMARY KEY, b_id int REFERENCES t_missing(id));
        ALTER TABLE t_unknown ADD CONSTRAINT pk PRIMARY KEY (id);
        """
        result = parse_ddl(ddl, "postgresql")

        assert list(result.schema.tables) == ["t_a"]  # 컬럼 없는 t_like는 등록에서 뺀다
        assert any("열 목록이 없는 CREATE TABLE" in w and "t_copy" in w for w in result.warnings)
        assert any("LIKE" in w and "t_like" in w for w in result.warnings)
        assert any("컬럼을 하나도 읽지 못한" in w and "t_like" in w for w in result.warnings)
        assert any("정의되지 않은 테이블" in w and "t_unknown" in w for w in result.warnings)
        assert any("참조 대상 테이블이 DDL에 없습니다" in w for w in result.warnings)
        # 대상이 DDL에 없어도 대상 컬럼이 명시되면 MCP처럼 관계는 남긴다
        assert result.schema.relationships == [{"from": "t_a.b_id", "to": "t_missing.id"}]

    def test_alter_add_column_and_redefinition(self):
        ddl = """
        CREATE TABLE t_a (id int);
        ALTER TABLE t_a ADD COLUMN note varchar(10) NOT NULL, ADD PRIMARY KEY (id);
        CREATE TABLE t_b (x int);
        CREATE TABLE t_b (y int);
        """
        result = parse_ddl(ddl, "postgresql")

        assert _columns(result, "t_a") == {
            "id": ("integer", False, True, None),
            "note": ("character varying", False, False, None),
        }
        assert [c.name for c in result.schema.tables["t_b"].columns] == ["y"]
        assert any("다시 정의" in w and "t_b" in w for w in result.warnings)

    def test_warning_list_is_capped(self):
        ddl = "\n".join(f"ALTER TABLE t_{i} ADD PRIMARY KEY (id);" for i in range(MAX_WARNINGS + 5))
        result = parse_ddl(ddl, "postgresql")

        assert len(result.warnings) == MAX_WARNINGS + 1
        assert result.warnings[-1] == "… 외 경고 5건"

    def test_unsupported_engine(self):
        with pytest.raises(ValueError, match="engine"):
            parse_ddl("CREATE TABLE t (id int);", "oracle")

    def test_strings_and_comments_do_not_split_statements(self):
        statements = split_statements(
            "CREATE TABLE t (a varchar(3) DEFAULT ';'); -- ; 주석\n/* ; */ SELECT 1;", "postgresql"
        )

        assert len(statements) == 2


# ──────────────────────────────────────────────
# MCP 수집과의 스냅샷 동등성 (핵심 계약)
# ──────────────────────────────────────────────


async def _mcp_snapshot(engine: str, tables: dict[str, FakeTable]) -> tuple[dict, dict]:
    session = FakeMCPSession()
    session.add_source("app_src", engine, tables)
    async with client_factory(session)("app_src") as client:
        return _snapshot_of(await client.get_full_schema())


def _table(columns: list[tuple[str, str, bool, bool]], fks=(), schema: str = "public") -> FakeTable:
    return FakeTable(list(columns), list(fks), schema)


@pytest.mark.parametrize(
    ("engine", "ddl", "mcp_tables"),
    [
        pytest.param("postgresql", PG_DUMP, {
            "t_node": _table([
                ("id", "integer", False, True), ("parent_id", "integer", True, False),
                ("node_type", "character varying", True, False),
                ("created", "timestamp without time zone", True, False),
                ("tags", "ARRAY", True, False), ("mood", "USER-DEFINED", True, False),
                ("amount", "numeric", True, False),
            ]),
            "t_asset": _table(
                [("id", "bigint", False, True), ("node_id", "integer", True, False),
                 ("ok", "boolean", True, False)],
                fks=[("node_id", "t_node", "id")],
            ),
            "ops.t_log": _table(
                [("seq", "bigint", False, True), ("body", "text", True, False)], schema="ops"
            ),
        }, id="postgresql"),
        pytest.param("db2", DB2_LOOK, {
            "T_NODE": _table([
                ("ID", "BIGINT", False, True), ("NAME", "VARCHAR", True, False),
                ("FLAG", "CHARACTER", False, False), ("TS", "TIMESTAMP", False, False),
                ("AMT", "DECIMAL", True, False),
            ], schema="APP"),
            "T_CHILD": _table(
                [("ID", "INTEGER", False, True), ("NODE_ID", "BIGINT", True, False)],
                fks=[("NODE_ID", "T_NODE", "ID")], schema="APP",
            ),
        }, id="db2"),
        pytest.param("mariadb", MARIADB_DUMP, {
            "t_item": _table([
                ("id", "int", False, True), ("name", "varchar", True, False),
                ("owner_id", "bigint", True, False), ("payload", "longtext", True, False),
                ("flag", "tinyint", False, False),
            ], fks=[("owner_id", "t_owner", "id")], schema="app"),
            "t_owner": _table([("id", "bigint", False, True)], schema="app"),
        }, id="mariadb"),
    ],
)
async def test_ddl_snapshot_hash_equals_mcp_collection(engine, ddl, mcp_tables):
    """같은 구조면 DDL 해석 스냅샷 = MCP 수집 스냅샷(해시·관계) — 이후 MCP 점검에 가짜 차이 0."""
    mcp_dict, mcp_snapshot = await _mcp_snapshot(engine, mcp_tables)
    ddl_dict, ddl_snapshot = _snapshot_of(parse_ddl(ddl, engine).schema)

    assert ddl_snapshot["hash"] == mcp_snapshot["hash"]
    assert sorted(ddl_snapshot["tables"]) == sorted(mcp_snapshot["tables"])
    assert ddl_dict["relationships"] == mcp_dict["relationships"]
