-- =============================================================================
-- POLESTAR 테스트 환경 DDL (PostgreSQL 버전)
-- 파일: testdata/pg/init/01_create_tables.sql
-- 설명: POLESTAR 스키마 및 테이블 생성
-- DB 엔진: PostgreSQL 14+
-- 인코딩: UTF-8
-- 원본: testdata/01_create_tables.sql (IBM DB2 11.5+)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. 스키마 생성
-- -----------------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS polestar;

-- -----------------------------------------------------------------------------
-- 2. CMM_RESOURCE 테이블 (59컬럼)
-- 인프라 리소스를 계층 구조로 관리하는 테이블
-- -----------------------------------------------------------------------------

CREATE TABLE polestar.cmm_resource (
    dtype                       VARCHAR(31) NOT NULL,
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    acl_id                      BIGINT NOT NULL,
    acl_manager_group_id        BIGINT,
    acl_manager_id              BIGINT,
    avail_status                INTEGER,
    ctime                       BIGINT,
    dtime                       BIGINT,
    description                 VARCHAR(4000),
    group_path                  VARCHAR(4000),
    haschildren                 SMALLINT,
    hostname                    VARCHAR(255),
    id_ancestry                 VARCHAR(2000),
    identifier                  VARCHAR(4000),
    importance_id               INTEGER NOT NULL DEFAULT 1,
    is_inherit_avail_depend     SMALLINT,
    is_inherit_custom_conf      SMALLINT,
    is_inherit_manager_zone     SMALLINT,
    inheritstatus               SMALLINT NOT NULL,
    inventorypollinginterval    INTEGER,
    invisible                   SMALLINT NOT NULL,
    ipaddress                   VARCHAR(255),
    lc                          INTEGER,
    location                    VARCHAR(255),
    longpollinginterval         INTEGER,
    mtime                       BIGINT,
    is_maintenance              SMALLINT,
    manager_zone                VARCHAR(255),
    mesurementpollinginterval   INTEGER,
    modifiedby                  VARCHAR(255),
    name                        VARCHAR(900) NOT NULL,
    optlock                     INTEGER,
    order_num                   INTEGER,
    parent_resource_id          BIGINT,
    platform_resource_id        BIGINT,
    pollingpolicy               INTEGER,
    priority                    INTEGER,
    resourceicon                VARCHAR(255),
    resource_key                VARCHAR(255) NOT NULL,
    resourcestatus              INTEGER,
    resource_type               VARCHAR(255) NOT NULL,
    resourcetypeversion         VARCHAR(255),
    service_resource_id         BIGINT,
    is_sync_desc                SMALLINT,
    is_sync_name                SMALLINT,
    uuid                        VARCHAR(255),
    version                     VARCHAR(255),
    system                      SMALLINT,
    avail_depend_resource_id    BIGINT,
    avail_depend_resource_id_2  BIGINT,
    connection_conf_id          BIGINT,
    custom_conf_id              BIGINT,
    realtime_info_id            BIGINT,
    resource_conf_id            BIGINT,
    resource_path_id            BIGINT,
    schedule_id                 BIGINT,
    resource_system_id          BIGINT,
    group_resource_id           BIGINT,
    business_group_resource_id  BIGINT
);

-- -----------------------------------------------------------------------------
-- 3. CORE_CONFIG_PROP 테이블 (12컬럼)
-- 에이전트/리소스 설정을 EAV 패턴으로 저장하는 테이블
-- -----------------------------------------------------------------------------

CREATE TABLE polestar.core_config_prop (
    dtype                   VARCHAR(31) NOT NULL,
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    errormessage            VARCHAR(255),
    name                    VARCHAR(255),
    time_stamp              BIGINT,
    stringvalue             TEXT,
    is_lob                  SMALLINT,
    stringvalue_short       VARCHAR(4000),
    configuration_id        BIGINT,
    parent_list_id          BIGINT,
    parent_map_id           BIGINT,
    propertydefinition_id   BIGINT NOT NULL
);

-- =============================================================================
-- 실행 완료 메시지
-- =============================================================================
-- DDL 실행 후 02_insert_cmm_resource.sql을 실행하세요.
