-- =============================================================================
-- POLESTAR 테스트 환경 DDL
-- 파일: testdata/01_create_tables.sql
-- 설명: POLESTAR 스키마 및 테이블 생성
-- DB 엔진: IBM DB2 11.5+
-- 인코딩: UTF-8
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. 스키마 생성
-- -----------------------------------------------------------------------------
-- DB2에서는 CREATE SCHEMA IF NOT EXISTS가 없으므로, 이미 존재하면 무시됩니다.
-- 스키마가 이미 있을 경우 SQL0601N 오류가 발생하지만 계속 진행 가능합니다.
CREATE SCHEMA POLESTAR;

-- -----------------------------------------------------------------------------
-- 2. CMM_RESOURCE 테이블 (59컬럼)
-- 인프라 리소스를 계층 구조로 관리하는 테이블
-- -----------------------------------------------------------------------------
-- 참고: 테스트 환경에서 아래 옵션으로 오류 발생 시 제거하세요.
--   - COMPRESS YES ADAPTIVE
--   - IN "SSNISND01R" INDEX IN "SSNISND01X"
--   - ORGANIZE BY ROW
-- -----------------------------------------------------------------------------

CREATE TABLE "POLESTAR"."CMM_RESOURCE"  (
    "DTYPE" VARCHAR(31 OCTETS) NOT NULL ,
    "ID" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
      START WITH +1
      INCREMENT BY +1
      MINVALUE +1
      MAXVALUE +9223372036854775807
      NO CYCLE
      CACHE 20
      NO ORDER ) ,
    "ACL_ID" BIGINT NOT NULL ,
    "ACL_MANAGER_GROUP_ID" BIGINT ,
    "ACL_MANAGER_ID" BIGINT ,
    "AVAIL_STATUS" INTEGER ,
    "CTIME" BIGINT ,
    "DTIME" BIGINT ,
    "DESCRIPTION" VARCHAR(4000 OCTETS) ,
    "GROUP_PATH" VARCHAR(4000 OCTETS) ,
    "HASCHILDREN" SMALLINT ,
    "HOSTNAME" VARCHAR(255 OCTETS) ,
    "ID_ANCESTRY" VARCHAR(2000 OCTETS) ,
    "IDENTIFIER" VARCHAR(4000 OCTETS) ,
    "IMPORTANCE_ID" INTEGER NOT NULL WITH DEFAULT 1 ,
    "IS_INHERIT_AVAIL_DEPEND" SMALLINT ,
    "IS_INHERIT_CUSTOM_CONF" SMALLINT ,
    "IS_INHERIT_MANAGER_ZONE" SMALLINT ,
    "INHERITSTATUS" SMALLINT NOT NULL ,
    "INVENTORYPOLLINGINTERVAL" INTEGER ,
    "INVISIBLE" SMALLINT NOT NULL ,
    "IPADDRESS" VARCHAR(255 OCTETS) ,
    "LC" INTEGER ,
    "LOCATION" VARCHAR(255 OCTETS) ,
    "LONGPOLLINGINTERVAL" INTEGER ,
    "MTIME" BIGINT ,
    "IS_MAINTENANCE" SMALLINT ,
    "MANAGER_ZONE" VARCHAR(255 OCTETS) ,
    "MESUREMENTPOLLINGINTERVAL" INTEGER ,
    "MODIFIEDBY" VARCHAR(255 OCTETS) ,
    "NAME" VARCHAR(900 OCTETS) NOT NULL ,
    "OPTLOCK" INTEGER ,
    "ORDER_NUM" INTEGER ,
    "PARENT_RESOURCE_ID" BIGINT ,
    "PLATFORM_RESOURCE_ID" BIGINT ,
    "POLLINGPOLICY" INTEGER ,
    "PRIORITY" INTEGER ,
    "RESOURCEICON" VARCHAR(255 OCTETS) ,
    "RESOURCE_KEY" VARCHAR(255 OCTETS) NOT NULL ,
    "RESOURCESTATUS" INTEGER ,
    "RESOURCE_TYPE" VARCHAR(255 OCTETS) NOT NULL ,
    "RESOURCETYPEVERSION" VARCHAR(255 OCTETS) ,
    "SERVICE_RESOURCE_ID" BIGINT ,
    "IS_SYNC_DESC" SMALLINT ,
    "IS_SYNC_NAME" SMALLINT ,
    "UUID" VARCHAR(255 OCTETS) ,
    "VERSION" VARCHAR(255 OCTETS) ,
    "SYSTEM" SMALLINT ,
    "AVAIL_DEPEND_RESOURCE_ID" BIGINT ,
    "AVAIL_DEPEND_RESOURCE_ID_2" BIGINT ,
    "CONNECTION_CONF_ID" BIGINT ,
    "CUSTOM_CONF_ID" BIGINT ,
    "REALTIME_INFO_ID" BIGINT ,
    "RESOURCE_CONF_ID" BIGINT ,
    "RESOURCE_PATH_ID" BIGINT ,
    "SCHEDULE_ID" BIGINT ,
    "RESOURCE_SYSTEM_ID" BIGINT ,
    "GROUP_RESOURCE_ID" BIGINT ,
    "BUSINESS_GROUP_RESOURCE_ID" BIGINT );

-- PRIMARY KEY
ALTER TABLE "POLESTAR"."CMM_RESOURCE" ADD CONSTRAINT "CMM_RESOURCE_PK" PRIMARY KEY ("ID");

-- -----------------------------------------------------------------------------
-- 3. CORE_CONFIG_PROP 테이블 (12컬럼)
-- 에이전트/리소스 설정을 EAV 패턴으로 저장하는 테이블
-- -----------------------------------------------------------------------------

CREATE TABLE "POLESTAR"."CORE_CONFIG_PROP"  (
    "DTYPE" VARCHAR(31 OCTETS) NOT NULL ,
    "ID" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
      START WITH +1
      INCREMENT BY +1
      MINVALUE +1
      MAXVALUE +9223372036854775807
      NO CYCLE
      CACHE 20
      NO ORDER ) ,
    "ERRORMESSAGE" VARCHAR(255 OCTETS) ,
    "NAME" VARCHAR(255 OCTETS) ,
    "TIME_STAMP" BIGINT ,
    "STRINGVALUE" CLOB(1073741824 OCTETS) LOGGED NOT COMPACT ,
    "IS_LOB" SMALLINT ,
    "STRINGVALUE_SHORT" VARCHAR(4000 OCTETS) ,
    "CONFIGURATION_ID" BIGINT ,
    "PARENT_LIST_ID" BIGINT ,
    "PARENT_MAP_ID" BIGINT ,
    "PROPERTYDEFINITION_ID" BIGINT NOT NULL );

-- PRIMARY KEY
ALTER TABLE "POLESTAR"."CORE_CONFIG_PROP" ADD CONSTRAINT "CORE_CONFIG_PROP_PK" PRIMARY KEY ("ID");

-- =============================================================================
-- 실행 완료 메시지
-- =============================================================================
-- DDL 실행 후 02_insert_cmm_resource.sql을 실행하세요.
